[package]
name = "mybloom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.xxhash-rust]
version = "0.8.5"
features = ["xxh32", "const_xxh32",]
